.. -*- rst -*-
.. vim: ft=rst

.. This rst format file contains commonly used link targets
   and name substitutions.  It may be included in many files,
   therefore it should only contain link targets and name
   substitutions.  Try grepping for "^\.\. _" to find plausible
   candidates for this list.

.. NOTE: reST targets are
   __not_case_sensitive__, so only one target definition is needed for
   regreg, REGREG, RegReg, etc...

.. regreg
.. _`regreg github`: http://github.com/regreg/regreg
.. _`regreg trunk`: http://github.com/regreg/regreg
.. _regreg pypi: http://pypi.python.org/pypi/regreg
.. _regreg issues: http://github.com/regreg/regreg/issues
.. _`regreg bugs`: http://github.com/regreg/regreg/issues
.. _regreg on travis: https://travis-ci.org/regreg/regreg
.. _nipy buildbot: http://nipy.bic.berkeley.edu
.. _try_branch.py: https://github.com/nipy/nibotmi/blob/master/install.rst#trying-a-set-of-changes-on-the-buildbots

.. Documentation tools
.. _graphviz: http://www.graphviz.org/
.. _Sphinx: http://sphinx.pocoo.org/
.. _`Sphinx reST`: http://sphinx.pocoo.org/rest.html
.. _reST: http://docutils.sourceforge.net/rst.html
.. _docutils: http://docutils.sourceforge.net

.. Licenses
.. _GPL: http://www.gnu.org/licenses/gpl.html
.. _BSD: http://www.opensource.org/licenses/bsd-license.php
.. _LGPL: http://www.gnu.org/copyleft/lesser.html
.. _MIT License: http://www.opensource.org/licenses/mit-license.php

.. Operating systems and distributions
.. _Debian: http://www.debian.org
.. _NeuroDebian: http://neuro.debian.net
.. _Ubuntu: http://www.ubuntu.com
.. _MacPorts: http://www.macports.org/

.. Working process
.. _github: http://github.com

.. Python packaging
.. _distutils: http://docs.python.org/2/library/distutils.html
.. _setuptools: http://pypi.python.org/pypi/setuptools
.. _distribute: http://pypi.python.org/pypi/distribute
.. _pip: http://pypi.python.org/pypi/pip
.. _pypi: http://pypi.python.org
.. _example pypi: http://packages.python.org/an_example_pypi_project/setuptools.html#intermezzo-pypirc-file-and-gpg
.. _github bdist_mpkg: https://github.com/matthew-brett/bdist_mpkg

.. Code support stuff
.. _pychecker: http://pychecker.sourceforge.net/
.. _pylint: http://www.logilab.org/project/pylint
.. _pyflakes: http://divmod.org/trac/wiki/DivmodPyflakes
.. _virtualenv: http://pypi.python.org/pypi/virtualenv
.. _git: http://www.git-scm.com/
.. _flymake: http://flymake.sourceforge.net/
.. _emacs_python_mode: http://www.emacswiki.org/cgi-bin/wiki/PythonMode
.. _doctest-mode: http://www.cis.upenn.edu/~edloper/projects/doctestmode/
.. _bazaar: http://bazaar-vcs.org/
.. _subversion: http://subversion.tigris.org/
.. _nose: http://nose.readthedocs.org/en/latest
.. _`python coverage tester`: http://nedbatchelder.com/code/modules/coverage.html

.. Other python projects
.. _numpy: http://numpy.scipy.org
.. _scipy: http://www.scipy.org
.. _cython: http://www.cython.org/
.. _ipython: http://ipython.org
.. _matplotlib: http://matplotlib.org
.. _python: https://www.python.org
.. _sympy: http://sympy.org
.. _pythonxy: http://www.pythonxy.com/
.. _python (x, y): http://www.pythonxy.com/
.. _Unofficial Windows binaries: http://www.lfd.uci.edu/~gohlke/pythonlibs

.. Not so python projects
.. _matlab: http://www.mathworks.com

.. Visualization
.. _vtk: http://www.vtk.org/

.. General software
.. _gcc: http://gcc.gnu.org
.. _xcode: http://developer.apple.com/TOOLS/xcode
.. _mingw: http://www.mingw.org
.. _cygwin: http://cygwin.com
.. _macports: http://www.macports.org/
.. _VTK: http://www.vtk.org/
.. _ITK: http://www.itk.org/
.. _swig: http://www.swig.org

.. Other organizations
.. _enthought: <http://www.enthought.com>
.. _kitware: http://www.kitware.com

.. Mathematical methods
.. _`wikipedia ICA`: http://en.wikipedia.org/wiki/Independent_component_analysis
.. _`wikipedia PCA`: http://en.wikipedia.org/wiki/Principal_component_analysis

.. Testing
.. _travis-ci: https://travis-ci.org
